// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgiRtrZ3wNY9gQ4OcLecqu1VK8BkYhaGQ',
    appId: '1:936298693568:web:b6307b5bfc348b069cbe25',
    messagingSenderId: '936298693568',
    projectId: 'baby-46fd5',
    authDomain: 'baby-46fd5.firebaseapp.com',
    storageBucket: 'baby-46fd5.appspot.com',
    measurementId: 'G-V4SW4YW0C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_gE9lpdUUESvJiIJmL7ooaiFELMfpCo',
    appId: '1:936298693568:android:5e9510018fbe32a89cbe25',
    messagingSenderId: '936298693568',
    projectId: 'baby-46fd5',
    storageBucket: 'baby-46fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRQBMl72Wceo6Pn0iz0gIglU11J0Zt2Tw',
    appId: '1:936298693568:ios:9524f88f26a1a99b9cbe25',
    messagingSenderId: '936298693568',
    projectId: 'baby-46fd5',
    storageBucket: 'baby-46fd5.appspot.com',
    iosBundleId: 'com.example.baby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRQBMl72Wceo6Pn0iz0gIglU11J0Zt2Tw',
    appId: '1:936298693568:ios:9524f88f26a1a99b9cbe25',
    messagingSenderId: '936298693568',
    projectId: 'baby-46fd5',
    storageBucket: 'baby-46fd5.appspot.com',
    iosBundleId: 'com.example.baby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgiRtrZ3wNY9gQ4OcLecqu1VK8BkYhaGQ',
    appId: '1:936298693568:web:d2c99e6d35b5b91c9cbe25',
    messagingSenderId: '936298693568',
    projectId: 'baby-46fd5',
    authDomain: 'baby-46fd5.firebaseapp.com',
    storageBucket: 'baby-46fd5.appspot.com',
    measurementId: 'G-PB25D4HL0C',
  );
}
